ORG 0000H
	LJMP 8000H
	ORG 8000H
		MOV R0,#04H
		AGAIN: MOV DPTR,#8500H
		MOV R1,#04H
		BACK: MOV R2,DPL
		MOVX A, @ DPTR
		MOV B,A
		INC DPTR
		MOVX A, @ DPTR
		CJNE A, B, NEXT
		AJMP SKIP
		NEXT: JNC SKIP
		MOV DPL, R2
		MOVX @ DPTR, A
		INC DPTR
		MOV A, B
		MOVX @DPTR, A 
		SKIP: DJNZ R1, BACK
		DJNZ R0, AGAIN 
		LCALL 0003H
		END
			
		
	